#cloud build
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - '-t'
      - 'gcr.io/$PROJECT_ID/$_SERVICE'
      - '--build-arg'
      - 'HF_TOKEN=$_HF_TOKEN'
      - '.'
images:
  - 'gcr.io/$PROJECT_ID/$_SERVICE'