name: 'Deploy to Cloud Run from Source'

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: 'llm-garage'
  REGION: 'us-central1'
  SERVICE: 'llm-garage-inference'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      
      #Change policy so service is publicly accessible
      - name: 'Set IAM Policy for Cloud Run'
        run: |
          gcloud beta run services add-iam-policy-binding \
            --region=${{ env.REGION }} \
            --member=allUsers \
            --role=roles/run.invoker \
            ${{ env.SERVICE }}

      - name: 'Build and Push Docker Image'
        run: |
          gcloud builds submit \
            --config cloudbuild.yaml \
            --substitutions _HF_TOKEN=${{ secrets.HF_TOKEN }},_SERVICE=${{ env.SERVICE }},_GEMINI_KEY=${{secrets.GEMINI_KEY}} \
            --project ${{ env.PROJECT_ID }} \

      - name: 'Deploy to Cloud Run'
        run: |
          gcloud run deploy ${{ env.SERVICE }} \
            --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }} \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --memory 4Gi